<?php $form = $this->form; ?>
<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form) ?>
<?php echo $this->formFile($form->get('image')); ?>
<?php echo $this->formElement($form->get('submit')); ?>
<?php echo $this->formElementErrors($form->get('image')); ?>
<?php echo $this->formElement($form->get('csrf')); ?>
<?php echo $this->formElementErrors($form->get('csrf')); ?>

<?php echo $this->form()->closeTag() ?>