<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('My social network'))->setSeparator(' - ')->setAutoEscape(false) ?>
        
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
        
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
        
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="/"><?php echo $this->translate('My social network') ?></a>
                    <div class="nav-collapse collapse">
                        <?php if ($this->loggedInUser !== null) : ?>
                            <?php $this->navigation('navigation')->findBy('route', 'wall')->setParams(array('username' => $this->loggedInUser->getUsername())); ?>
                            <?php $this->navigation('navigation')->findBy('route', 'feeds')->setParams(array('username' => $this->loggedInUser->getUsername())); ?>
                        <?php endif; ?>
                        <?php echo $this->navigation('navigation')->menu()->setUlClass('nav')->setAcl($this->acl)->setRole($this->userRole)->renderMenu(); ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="container wrapper">
            <?php echo $this->flashMessengerHelper() ?>
            <?php echo $this->content; ?>
        </div>
        <footer>
            <div class="container fluid-row">
                <?php echo $this->translate('Welcome to my Social Network | Learn how to create a Social Network with ZF2 &copy; 2013') ?>
            </div>
        </footer>
        
        <?php echo $this->inlineScript() ?>
    </body>
</html>
