<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid">
            <!-- Profile section -->
            <div class="span3 well" id="subscriptions">
                <section class="profile-rss">
                    <a href="<?php echo $this->url('wall', array('username' => $user->getUsername())) ?>" title="<?php printf('%s %s', $user->getName(), $user->getSurname())  ?>" class="profile-picture">
                        <img src="<?php echo $user->getAvatar()->getUrl() ?>" alt="<?php printf('%s %s', $user->getName(), $user->getSurname())  ?>" width="60px" />
                    </a>
                    <a href="<?php echo $this->url('wall', array('username' => $user->getUsername())) ?>" title="<?php printf('%s %s', $user->getName(), $user->getSurname()) ?>" class="profile-name">
                        <?php printf('%s %s', $user->getName(), $user->getSurname()) ?>
                    </a>
                </section>
                <?php if (count($feedsMenu->getPages()) > 0) : ?>
                    <section>
                        <?php echo $this->navigation($feedsMenu)->menu()->setPartial('partials/menu-feed-container.phtml') ?>
                    </section>
                <?php endif; ?>
                <section class="add-subscription">
                    <?php echo $this->partial('forms/subscribe-form.phtml', array('form' => $subscribeForm)) ?>
                </section>
            </div>
            <!-- Wall profile -->
            <div class="span9" id="articles">
                <?php if (isset($paginator) && $paginator->getCurrentItemCount() > 0) : ?>
                    <section class="rss-stream clearfix">
                        <div class="pull-left">
                            <h2><?php echo $feed->getTitle() ?></h2>
                            <span><strong><?php echo $this->translate('URL:') ?> </strong><?php echo $feed->getUrl() ?></span>
                        </div>
                        <?php echo $this->partial('forms/unsubscribe-form.phtml', array('form' => $unsubscribeForm)) ?>
                    </section>
                    <?php foreach($paginator as $a) : ?>
                        <article class="well">
                            <h2><a href="<?php echo $a->getUrl() ?>" title="<?php echo $a->getTitle() ?>"><?php echo $a->getTitle() ?></a></h2>
                            <div class="lead-info">
                                <span><strong><?php echo $this->translate('Date:') ?></strong> <?php echo $a->getCreatedAt()->format('jS \of F Y h:i:s A') ?></span>
                                <?php if ($a->getAuthor() !== null) : ?>
                                    <span><strong><?php echo $this->translate('Author:') ?></strong> <?php echo $a->getAuthor() ?></span>
                                <?php endif; ?>
                            </div>
                            <div class="article-info">
                                <p><?php echo $a->getContent() ?></p>
                            </div>
                        </article>
                    <?php endforeach; ?>
                    <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator/default', array('route' => 'feeds', 'routeParams' => array('feed_id' => $feedId, 'username' => $user->getUsername()))); ?>
                <?php else : ?>
                    <article class="well">
                        <div class="article-info">
                            <?php echo $this->translate('You\'ll see the articles soon...') ?>
                        </div>
                    </article>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>