<div style="color: #444;font-family: Arial, sans-serif;font-size: 16px;padding: 0 20px; width:560px;">
    <p style="margin: 20px 0 20px 0; line-height:22px;">
        Hi <?php echo $recipientName ?>,
        <?php echo $authorName ?> has posted a new comment on your wall!
    </p>
    
    <p style="margin: 0 0 20px 0;line-height:15px;font-size: 13px;">
        Best regards,<br />
        My Social Network
    </p>
</div>
