<div style="background:#d7e7f3;padding:30px 0 30px 0">
    <center>
        <div style="width:600px;background:#ffffff;margin:0 auto;">
            <table border="0" cellpadding="0" cellspacing="0" width="620" style="width:620px">
                <tr>
                    <td>
                        <?php echo $content ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div style="color: #999;font-family: Arial, sans-serif;font-size: 11px;line-height: 1.4em;border-top: 1px solid #eee;margin: 20px 20px 0 20px; padding:10px 0 20px 0; width:560px">
                            <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                <tr>
                                    <td valign="top">
                                            You are receiving this mail because you are a My Social Network user.<br/>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </center>
</div>